import "server-only";

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const serverEnv = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    POSTGRES_PRISMA_URL: z.string().min(1, "POSTGRES_PRISMA_URL is required"),
    POSTGRES_URL_NON_POOLING: z.string().min(1, "POSTGRES_URL_NON_POOLING is required"),
    SUPABASE_URL: z.string().optional(),
    SUPABASE_ANON_KEY: z.string().optional(),
    SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
    OPENAI_API_KEY: z.string().optional(),
    OPENAI_COPILOT_MODEL: z.string().optional(),
    RESEND_API_KEY: z.string().optional(),
    RESEND_FROM_EMAIL: z.string().optional(),
    TWILIO_ACCOUNT_SID: z.string().optional(),
    TWILIO_AUTH_TOKEN: z.string().optional(),
    TWILIO_FROM_NUMBER: z.string().optional(),
    TWILIO_ORGANIZATION_ID: z.string().optional(),
    JOB_RUNNER_TOKEN: z.string().optional(),
    DEV_ORGANIZATION_ID: z.string().optional(),
    DEV_USER_ID: z.string().optional(),
    DEV_AUTH_BYPASS: z.string().optional(),
    ENABLE_AI_SUGGESTIONS: z.string().optional(),
    GOOGLE_CALENDAR_CLIENT_ID: z.string().optional(),
    GOOGLE_CALENDAR_CLIENT_SECRET: z.string().optional(),
    S3_BUCKET: z.string().optional(),
    S3_REGION: z.string().optional(),
    S3_ACCESS_KEY_ID: z.string().optional(),
    S3_SECRET_ACCESS_KEY: z.string().optional(),
    S3_ENDPOINT: z.string().optional(),
    S3_PUBLIC_URL: z.string().optional(),
    ZILLOW_RENTAL_FEED_ENABLED: z.string().optional(),
    ZILLOW_RENTAL_FEED_ORG_ID: z.string().optional(),
    ZILLOW_RENTAL_FEED_TOKEN: z.string().optional(),
    ZILLOW_RENTAL_FEED_CONTACT_NAME: z.string().optional(),
    ZILLOW_RENTAL_FEED_CONTACT_EMAIL: z.string().optional(),
    ZILLOW_RENTAL_FEED_CONTACT_PHONE: z.string().optional(),
    ZILLOW_RENTAL_FEED_COMPANY_CITY: z.string().optional(),
    ZILLOW_RENTAL_FEED_COMPANY_STATE: z.string().optional(),
    ZILLOW_RENTAL_FEED_COMPANY_WEBSITE: z.string().optional(),
    ZILLOW_RENTAL_FEED_COMPANY_LOGO_URL: z.string().optional(),
    VERCEL_URL: z.string().optional(),
    APPLICATION_PHONE_DEDUPE_BYPASS_E164: z.string().optional(),
    APPLICATION_PHONE_DEDUPE_BYPASS_REQUIRE_PREVIEW: z.string().optional(),
    APPLICATION_PHONE_DEDUPE_BYPASS_ORG_IDS: z.string().optional(),
    VERCEL_ENV: z.string().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
    POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_COPILOT_MODEL: process.env.OPENAI_COPILOT_MODEL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_FROM_NUMBER: process.env.TWILIO_FROM_NUMBER,
    TWILIO_ORGANIZATION_ID: process.env.TWILIO_ORGANIZATION_ID,
    JOB_RUNNER_TOKEN: process.env.JOB_RUNNER_TOKEN,
    DEV_ORGANIZATION_ID: process.env.DEV_ORGANIZATION_ID,
    DEV_USER_ID: process.env.DEV_USER_ID,
    DEV_AUTH_BYPASS: process.env.DEV_AUTH_BYPASS,
    ENABLE_AI_SUGGESTIONS: process.env.ENABLE_AI_SUGGESTIONS,
    GOOGLE_CALENDAR_CLIENT_ID: process.env.GOOGLE_CALENDAR_CLIENT_ID,
    GOOGLE_CALENDAR_CLIENT_SECRET: process.env.GOOGLE_CALENDAR_CLIENT_SECRET,
    S3_BUCKET: process.env.S3_BUCKET,
    S3_REGION: process.env.S3_REGION,
    S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
    S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_PUBLIC_URL: process.env.S3_PUBLIC_URL,
    ZILLOW_RENTAL_FEED_ENABLED: process.env.ZILLOW_RENTAL_FEED_ENABLED,
    ZILLOW_RENTAL_FEED_ORG_ID: process.env.ZILLOW_RENTAL_FEED_ORG_ID,
    ZILLOW_RENTAL_FEED_TOKEN: process.env.ZILLOW_RENTAL_FEED_TOKEN,
    ZILLOW_RENTAL_FEED_CONTACT_NAME: process.env.ZILLOW_RENTAL_FEED_CONTACT_NAME,
    ZILLOW_RENTAL_FEED_CONTACT_EMAIL: process.env.ZILLOW_RENTAL_FEED_CONTACT_EMAIL,
    ZILLOW_RENTAL_FEED_CONTACT_PHONE: process.env.ZILLOW_RENTAL_FEED_CONTACT_PHONE,
    ZILLOW_RENTAL_FEED_COMPANY_CITY: process.env.ZILLOW_RENTAL_FEED_COMPANY_CITY,
    ZILLOW_RENTAL_FEED_COMPANY_STATE: process.env.ZILLOW_RENTAL_FEED_COMPANY_STATE,
    ZILLOW_RENTAL_FEED_COMPANY_WEBSITE: process.env.ZILLOW_RENTAL_FEED_COMPANY_WEBSITE,
    ZILLOW_RENTAL_FEED_COMPANY_LOGO_URL: process.env.ZILLOW_RENTAL_FEED_COMPANY_LOGO_URL,
    VERCEL_URL: process.env.VERCEL_URL,
    APPLICATION_PHONE_DEDUPE_BYPASS_E164: process.env.APPLICATION_PHONE_DEDUPE_BYPASS_E164,
    APPLICATION_PHONE_DEDUPE_BYPASS_REQUIRE_PREVIEW:
      process.env.APPLICATION_PHONE_DEDUPE_BYPASS_REQUIRE_PREVIEW,
    APPLICATION_PHONE_DEDUPE_BYPASS_ORG_IDS: process.env.APPLICATION_PHONE_DEDUPE_BYPASS_ORG_IDS,
    VERCEL_ENV: process.env.VERCEL_ENV,
  },
  emptyStringAsUndefined: true,
});
